[[appendix-neo4j-export]]
=== Exporting to Neo4J

While Ontrack https://github.com/nemerosa/ontrack/issues/282[v4] will use
https://neo4j.com/[Neo4J] as back-end, it is already possible to export to
complete Ontrack data as a set of CSV files suitable to be imported into this
graph database using the
https://neo4j.com/docs/operations-manual/current/tutorial/import-tool/[import tool].

TODO Exporting the data

[[appendix-neo4j-export-convert]]
==== Converting the data using a Docker container

Considering that all files have been exported into a `$CSV` directory,
you can run the following command to convert all the CSV files into a
Neo4J database:

[source,bash]
----
docker run \
   --rm \
   --volume $CSV:/import \
   --volume `pwd`/export:/export \
   neo4j:3.1.1 \
   bin/neo4j-import \
      --into /export \
      --delimeter ',' \
      --nodes /import/nodes/Project.csv \
      --nodes /import/nodes/Branch.csv
----

WARNING: One cannot use `--nodes '/import/nodes/.*.csv'` because node `ID`s use ID spaces and files must be separated.

TODO Importing relationships

[[appendix-neo4j-export-using]]
==== Using the exported data

Assuming the converted files are available in the `$EXPORT` directory, you can move this directory as being
the graph database itself at `<neo4j-home>/data/databases/graph.db`.

Using Docker to launch the database, this would give:

[source,bash]
----
mkdir -p data/databases
mv $EXPORT data/databases/graph.db
docker run --detach \
    --publish=7474:7474 \
    --publish=7687:7687 \
    --name neo4j \
    --volume `pwd`/data:/data \
    neo4j:3.1.1
----
